In [142]:
import numpy as np

## create ndimensional array


In [143]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [144]:
print(type(a))

<class 'numpy.ndarray'>


In [23]:
# 2ndimensopnal array
two_dimension=np.array([[1,2,3],[4,5,6]])
two_dimension

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
type(two_dimension)

numpy.ndarray

In [27]:
zero_array=np.zeros((2,3))

In [28]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
one_dimension=np.ones((3,3))

In [31]:
type(one_dimension)

numpy.ndarray

#identity matrix where diaognal enties are 1 and non-diaognal are zero

In [34]:
identity_matrix=np.identity(3)

In [35]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# arange function
araned_array=np.arange(10)
araned_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# last value index
stop_array=np.arange(10,20)

In [39]:
stop_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
# stoping index
stop_index=np.arange(10,40,2)

In [41]:
stop_index

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [42]:
lin_space=np.linspace(10,20,10)
lin_space

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [43]:
copy_array=np.copy(zero_array)
copy_array

array([[0., 0., 0.],
       [0., 0., 0.]])

## Attributes

In [44]:
arr_9=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
arr_9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr_9.shape

(3, 3)

In [47]:
arr_9.ndim

2

In [51]:
three_dimension=np.array([[[10,20,30],[40,50,60],[40,50,60]]])

In [52]:
three_dimension

array([[[10, 20, 30],
        [40, 50, 60],
        [40, 50, 60]]])

In [55]:
three_dimension.ndim

3

## Size

In [56]:
# it return row*column
three_dimension.size

9

## itemsize

In [58]:
# it return memotry occupied by items if it is int then 4 if it is float then 8 
three_dimension.itemsize

4

In [60]:
three_dimension.dtype

dtype('int32')

## astype

In [61]:
# astype convert all data to provided type
astype_lin_space=np.copy(lin_space)

In [62]:
astype_lin_space.astype('int32')

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

## Python List vs numpy 

In [64]:
# fast,convenient,less memory
list=range(30)
arr11=np.arange(30)


In [65]:
import sys


In [66]:
sys.getsizeof(87)*len(list)

840

In [67]:
arr11.itemsize*arr11.size

120

In [89]:
import time

In [92]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
res=[(x,y) for x,y in zip(x,y)]
print(time.time()-start_time)

1.7544147968292236


In [93]:
# nummpy array
x=np.arange(10000000)
y=np.arange(10000000,20000000)
start_time=time.time()
res=x+y
print(time.time()-start_time)

0.4186515808105469


## indexing sliceing

In [114]:
arr12=np.arange(24).reshape(6,4)

In [115]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [119]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [127]:
arr12[2:4,1:3]
# pay attentantion that last index get ignore

array([[ 9, 10],
       [13, 14]])

In [128]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [130]:
# Iteration

for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [141]:
for i in np.nditer(arr12):
    print(i*i)

0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529


In [156]:
two_matrix=np.array([[10,20,30],[40,50,60]])
two_matrix

array([[10, 20, 30],
       [40, 50, 60]])

In [157]:
res=two_matrix.reshape(3,2)
res

array([[10, 20],
       [30, 40],
       [50, 60]])

In [166]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,100,6,7,8,9])
arr2>=3

array([ True,  True,  True,  True,  True,  True])

## dot product

In [27]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
print("arr3",arr3)
print(".","arr4",arr4,"=====")
print(arr3.dot(arr4))

arr3 [[0 1 2]
 [3 4 5]]
. arr4 [[ 6  7]
 [ 8  9]
 [10 11]] =====
[[ 28  31]
 [100 112]]


In [171]:
arr3.min()

0

In [172]:
arr3.max()

5

In [175]:
arr3.sum(axis=0)

array([3, 5, 7])

In [177]:
arr3.mean()

2.5

In [179]:
arr3.std()

1.707825127659933

In [181]:
np.median(arr4)

8.5

In [192]:
np.tan(arr4)

array([[  -0.29100619,    0.87144798],
       [  -6.79971146,   -0.45231566],
       [   0.64836083, -225.95084645]])

## Ravel

In [30]:
arr4.ravel()
# convert into one dimesion array

array([ 6,  7,  8,  9, 10, 11])

In [32]:
arr4.transpose()
# row becomes column and columns become row

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [33]:
np.transpose(arr4)

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [34]:
arr5=np.array([[10,20,30],[40,50,60]])
arr6=np.array([[10,20,30],[40,50,60]])
res=np.hstack((arr5,arr6))
res

array([[10, 20, 30, 10, 20, 30],
       [40, 50, 60, 40, 50, 60]])

In [203]:
arr5=np.array([[10,20,30],[40,50,60]])
arr6=np.array([[10,20,30],[40,50,60]])
res=np.vstack((arr5,arr6))
res

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])

In [205]:
arr8=np.arange(24).reshape(6,4)
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

## Boolean Indexing


In [208]:
# only items left for which condition is true
even=arr8[arr8%2==0]
odd=arr8[arr8%2!=0]

In [209]:
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [210]:
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [1]:
import numpy as np

In [8]:
arr1=np.array([[10,20,30],[10,20,30]])

In [9]:
arr1

array([[10, 20, 30],
       [10, 20, 30]])

In [14]:
num=np.arange(18).reshape(6,3)

In [15]:
num

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [24]:
for i in np.nditer(num):
    print(i*i)

0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
